# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'TheNewsCarlosCavalcanti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheNewsCarlosCavalcanti
  pod 'Alamofire', '= 5.4.3'	

  target 'TheNewsCarlosCavalcantiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheNewsCarlosCavalcantiUITests' do
    # Pods for testing
  end

end
